export const mockOrders = [
    {
        _id: "ORD001",
        orderNumber: "CK-2025-001",
        items: [
            {
                name: "Chicken Biryani",
                pic: "/assets/foods/biryani.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Main Course",
            },
            {
                name: "Coke",
                pic: "/assets/foods/coke.jpg",
                quantity: 2,
                price: 50,
                total: 100,
                category: "Beverage",
            },
            {
                name: "Chocolate Cake",
                pic: "/assets/foods/cake.jpg",
                quantity: 1,
                price: 650,
                total: 650,
                category: "Dessert",
            },
        ],
        totalAmount: 980,
        status: "delivered",
        paymentStatus: "paid",
        paymentMethod: "card",
        orderDate: "2025-06-15T10:30:00Z",
        deliveryDate: "2025-06-15T11:15:00Z",
        customerDetails: {
            name: "John Doe",
            phone: "01234567890",
            address: "123 Main St, Chittagong",
        },
        restaurantName: "Spice Garden Kitchen",
    },
    {
        _id: "ORD002",
        orderNumber: "CK-2025-002",
        items: [
            {
                name: "Beef Burger",
                pic: "/assets/foods/burger.jpg",
                quantity: 1,
                price: 300,
                total: 300,
                category: "Main Course",
            },
            {
                name: "Sprite",
                pic: "/assets/foods/sprite.jpg",
                quantity: 2,
                price: 60,
                total: 120,
                category: "Beverage",
            },
            {
                name: "Fries",
                pic: "/assets/foods/fries.jpg",
                quantity: 2,
                price: 180,
                total: 360,
                category: "Sides",
            },
        ],
        totalAmount: 560,
        status: "preparing",
        paymentStatus: "paid",
        paymentMethod: "bkash",
        orderDate: "2025-06-19T14:20:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "Jane Smith",
            phone: "01987654321",
            address: "456 Oak Ave, Chittagong",
        },
        restaurantName: "Burger House",
    },
    {
        _id: "ORD003",
        orderNumber: "CK-2025-003",
        items: [
            {
                name: "Grilled Chicken",
                pic: "/assets/foods/grilled.jpg",
                quantity: 1,
                price: 450,
                total: 450,
                category: "Main Course",
            },
            {
                name: "Lassi",
                pic: "/assets/foods/lassi.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Beverage",
            },
        ],
        totalAmount: 830,
        status: "cancelled",
        paymentStatus: "refunded",
        paymentMethod: "nagad",
        orderDate: "2025-06-18T19:45:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "Mike Johnson",
            phone: "01765432109",
            address: "789 Pine St, Chittagong",
        },
        restaurantName: "Pizza Corner",
    },
    {
        _id: "ORD004",
        orderNumber: "CK-2025-004",
        items: [
            {
                name: "Grilled Chicken",
                pic: "/assets/foods/grilled.jpg",
                quantity: 1,
                price: 450,
                total: 450,
                category: "Main Course",
            },
            {
                name: "Lassi",
                pic: "/assets/foods/Lassi.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Beverage",
            },
        ],
        totalAmount: 895,
        status: "out_for_delivery",
        paymentStatus: "paid",
        paymentMethod: "cash",
        orderDate: "2025-06-19T12:00:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "Sarah Wilson",
            phone: "01654321098",
            address: "321 Elm St, Chittagong",
        },
        restaurantName: "Spice Garden Kitchen",
    },
    {
        _id: "ORD005",
        orderNumber: "CK-2025-005",
        items: [
            {
                name: "Chicken Biryani",
                pic: "/assets/foods/biryani.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Main Course",
            },
            {
                name: "Coke",
                pic: "/assets/foods/coke.jpg",
                quantity: 2,
                price: 50,
                total: 100,
                category: "Beverage",
            },
            {
                name: "Chocolate Cake",
                pic: "/assets/foods/cake.jpg",
                quantity: 1,
                price: 650,
                total: 650,
                category: "Dessert",
            },
        ],
        totalAmount: 600,
        status: "confirmed",
        paymentStatus: "paid",
        paymentMethod: "card",
        orderDate: "2025-06-19T13:30:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "David Brown",
            phone: "01543210987",
            address: "654 Maple Ave, Chittagong",
        },
        restaurantName: "Asian Delights",
    },
    {
        _id: "ORD006",
        orderNumber: "CK-2025-005",
        items: [
            {
                name: "Chicken Biryani",
                pic: "/assets/foods/biryani.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Main Course",
            },
            {
                name: "Coke",
                pic: "/assets/foods/coke.jpg",
                quantity: 2,
                price: 50,
                total: 100,
                category: "Beverage",
            },
            {
                name: "Chocolate Cake",
                pic: "/assets/foods/cake.jpg",
                quantity: 1,
                price: 650,
                total: 650,
                category: "Dessert",
            },
        ],
        totalAmount: 600,
        status: "pending",
        paymentStatus: "unpaid",
        paymentMethod: "COD",
        orderDate: "2025-06-19T13:30:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "David Brown",
            phone: "01543210987",
            address: "654 Maple Ave, Chittagong",
        },
        restaurantName: "Asian Delights",
    },
];