export const mockOrders = [
    {
        _id: "ORD001",
        orderNumber: "CK-2025-001",
        items: [
            { name: "Chicken Biryani", quantity: 2, price: 450 },
            { name: "Raita", quantity: 1, price: 80 },
        ],
        totalAmount: 980,
        status: "delivered",
        paymentStatus: "paid",
        paymentMethod: "card",
        orderDate: "2025-06-15T10:30:00Z",
        deliveryDate: "2025-06-15T11:15:00Z",
        customerDetails: {
            name: "John Doe",
            phone: "01234567890",
            address: "123 Main St, Chittagong",
        },
        restaurantName: "Spice Garden Kitchen",
    },
    {
        _id: "ORD002",
        orderNumber: "CK-2025-002",
        items: [
            { name: "Beef Burger", quantity: 1, price: 320 },
            { name: "French Fries", quantity: 1, price: 120 },
            { name: "Coke", quantity: 2, price: 60 },
        ],
        totalAmount: 560,
        status: "preparing",
        paymentStatus: "paid",
        paymentMethod: "bkash",
        orderDate: "2025-06-19T14:20:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "Jane Smith",
            phone: "01987654321",
            address: "456 Oak Ave, Chittagong",
        },
        restaurantName: "Burger House",
    },
    {
        _id: "ORD003",
        orderNumber: "CK-2025-003",
        items: [
            { name: "Chicken Pizza", quantity: 1, price: 680 },
            { name: "Garlic Bread", quantity: 1, price: 150 },
        ],
        totalAmount: 830,
        status: "cancelled",
        paymentStatus: "refunded",
        paymentMethod: "nagad",
        orderDate: "2025-06-18T19:45:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "Mike Johnson",
            phone: "01765432109",
            address: "789 Pine St, Chittagong",
        },
        restaurantName: "Pizza Corner",
    },
    {
        _id: "ORD004",
        orderNumber: "CK-2025-004",
        items: [
            { name: "Mutton Curry", quantity: 1, price: 520 },
            { name: "Basmati Rice", quantity: 2, price: 120 },
            { name: "Naan", quantity: 3, price: 45 },
        ],
        totalAmount: 895,
        status: "out_for_delivery",
        paymentStatus: "paid",
        paymentMethod: "cash",
        orderDate: "2025-06-19T12:00:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "Sarah Wilson",
            phone: "01654321098",
            address: "321 Elm St, Chittagong",
        },
        restaurantName: "Spice Garden Kitchen",
    },
    {
        _id: "ORD005",
        orderNumber: "CK-2025-005",
        items: [
            { name: "Fried Rice", quantity: 1, price: 280 },
            { name: "Chicken Chow Mein", quantity: 1, price: 320 },
        ],
        totalAmount: 600,
        status: "confirmed",
        paymentStatus: "paid",
        paymentMethod: "card",
        orderDate: "2025-06-19T13:30:00Z",
        deliveryDate: null,
        customerDetails: {
            name: "David Brown",
            phone: "01543210987",
            address: "654 Maple Ave, Chittagong",
        },
        restaurantName: "Asian Delights",
    },
];