export const reviews = [
    {
        id: 1,
        dish: "Classic Beef Burger",
        category: "Burger",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
        reviewer: {
            name: "Roberto Jr.",
            role: "Customer",
            review: "Juicy and flavorful! One of the best burgers I’ve had recently. Would recommend the triple patty.",
            avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50&h=50&fit=crop&crop=face",
        },
        rating: 4.5,
        status: "pending",
    },
    {
        id: 2,
        dish: "Pepperoni Pizza",
        category: "Pizza",
        image: "https://images.unsplash.com/photo-1601924582975-4b11cbbf4916?auto=format&fit=crop&w=800&q=80",
        reviewer: {
            name: "Linda Smith",
            role: "Customer",
            review: "Loved the crispy crust and generous pepperoni. Will definitely order again!",
            avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&h=50&fit=crop&crop=face",
        },
        rating: 4.8,
        status: "pending",
    },
    {
        id: 3,
        dish: "Fancy Truffle Fries",
        category: "fancy fry",
        image: "https://images.unsplash.com/photo-1562967916-eb82221dfb15?auto=format&fit=crop&w=800&q=80",
        reviewer: {
            name: "Chris Thompson",
            role: "Customer",
            review: "Really elevated flavor for fries. The truffle aroma is perfect, and cheese adds great balance.",
            avatar: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=50&h=50&fit=crop&crop=face",
        },
        rating: 4.6,
        status: "pending",
    },
    {
        id: 4,
        dish: "Club Sandwich",
        name: "James Kowalski",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
        rating: 3.5,
        tags: ["Fresh Ingredients", "Quick Delivery"],
        text: "Had this with colleagues. Good sandwich quality, fresh ingredients. Came warm and packed well.",
        date: "2 days ago",
    },
    {
        id: 5,
        dish: "Chicken Chow Mein",
        name: "James Kowalski",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
        rating: 4.0,
        tags: ["Well Cooked", "Tasty"],
        text: "Tastes authentic. Noodles were perfectly cooked and balanced with veggies. Loved the soy flavor.",
        date: "3 days ago",
    },
    {
        id: 6,
        dish: "Iced Cold Coffee",
        name: "James Kowalski",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
        rating: 4.2,
        tags: ["Refreshing", "Sweet"],
        text: "Cold and smooth. Great balance of coffee and cream. Perfect drink for hot afternoons!",
        date: "1 week ago",
    },
];
