export const orders = [
    {
        oid: "ORD001",
        name: "Rabiul Rafee",
        email: "rafee@example.com",
        number: "+8801556789432",
        address: "House #12, Road #4, Dhanmondi, Dhaka",
        date: "2025-06-20 14:25",
        note: "Please deliver between 6 PM and 7 PM. Contact before arrival.",
        amount: 1250,
        status: "Completed",
        items: [
            {
                name: "Chicken Biryani",
                pic: "/assets/foods/biryani.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Main Course",
            },
            {
                name: "Coke",
                pic: "/assets/foods/coke.jpg",
                quantity: 2,
                price: 50,
                total: 100,
                category: "Beverage",
            },
            {
                name: "Chocolate Cake",
                pic: "/assets/foods/cake.jpg",
                quantity: 1,
                price: 650,
                total: 650,
                category: "Dessert",
            },
        ],
    },
    {
        oid: "ORD002",
        name: "Ayesha Khan",
        email: "ayesha@example.com",
        number: "+8801556789432",
        address: "Flat 3B, Nasirabad Housing, Chittagong",
        date: "2025-06-19 11:10",
        note: "Do not include onions in any item.",
        amount: 780,
        status: "Pending",
        items: [
            {
                name: "Beef Burger",
                pic: "/assets/foods/burger.jpg",
                quantity: 1,
                price: 300,
                total: 300,
                category: "Main Course",
            },
            {
                name: "Sprite",
                pic: "/assets/foods/sprite.jpg",
                quantity: 2,
                price: 60,
                total: 120,
                category: "Beverage",
            },
            {
                name: "Fries",
                pic: "/assets/foods/fries.jpg",
                quantity: 2,
                price: 180,
                total: 360,
                category: "Sides",
            },
        ],
    },
    {
        oid: "ORD003",
        name: "Tanvir Ahmed",
        email: "tanvir@example.com",
        number: "+8801556789432",
        address: "Shibgonj, Ambarkhana, Sylhet",
        date: "2025-06-18 17:40",
        note: "Cancelled due to late delivery notice.",
        amount: 950,
        status: "Cancelled",
        items: [
            {
                name: "Grilled Chicken",
                pic: "/assets/foods/grilled.jpg",
                quantity: 1,
                price: 450,
                total: 450,
                category: "Main Course",
            },
            {
                name: "Lassi",
                pic: "/assets/foods/lassi.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Beverage",
            },
        ],
    },
    {
        oid: "ORD004",
        name: "Farah Khan",
        email: "farah@example.com",
        number: "+8801556789432",
        address: "Beach View Tower, Kolatoli, Cox's Bazar",
        date: "2025-06-21 09:00",
        note: "Leave at the reception if customer unavailable.",
        amount: 950,
        status: "On Delivery",
        items: [
            {
                name: "Grilled Chicken",
                pic: "/assets/foods/grilled.jpg",
                quantity: 1,
                price: 450,
                total: 450,
                category: "Main Course",
            },
            {
                name: "Lassi",
                pic: "/assets/foods/Lassi.jpg",
                quantity: 2,
                price: 250,
                total: 500,
                category: "Beverage",
            },
        ],
    },
];
